### PR TITLE
Support union with are same subtypes with SNMP

### PR DESCRIPTION
**Pull request by StasSt-siklu**
Support yang type union with are same subtypes with SNMP

### CODE REVIEW

**Comment by StasSt-siklu** [comment]
> Looks good, thanks for the contribution. Just please adapt to style guidelines in https://github.com/clicon/clixon/blob/master/CONTRIBUTING.md of the two functions is_same_subtypes_union() and yang_type_to_snmp(). This includes the style of function declarations , curly brackets not on next line (`if () {`), separate documents retvals(0 and 1) Also seems test/test_snmp_union.sh has not execute bit set?

**Comment by olofhagsand** [comment]
@StasSt-siklu may I ask why you close this PR, do you not want it merged?

**Comment by StasSt-siklu** [comment]
Hi Olof. No. we want to merge this PR

**Comment by StasSt-siklu** [comment]
Good day Olof. Pls merge this PR

**Pull request merged**
