### PR TITLE
Scalars do not have a .0 suffix

### PR DESCRIPTION
**Pull request by StasSt-siklu**
Fix Scalars do not have a .0 suffix
Added .0 for scalar without table OIDs.

Changed snmp tests in files test_snmp_get.sh, test_snmp_set.sh, test_snmp_system.sh

### CODE REVIEW

**Comment by StasSt-siklu** [comment]
For testing only

**Comment by StasSt-siklu** [comment]
Hi.
Please review this PR.
I remove "sysUpTime" test in the file test_snmp_system.sh because after adding suffix ".0" to "SNMPv2-MIB::sysUpTime" 
it changes the name to DISMAN-EVENT-MIB::sysUpTimeInstance.
SNMPv2-MIB::sysUpTime OID - 1.3.6.1.2.1.1.3
DISMAN-EVENT-MIB::sysUpTimeInstance OID: 1.3.6.1.2.1.1.3.0 (from DISMAN-EVENT-MIB.mib).

**Comment by shmuelhazan** [comment]
> Hi. Please review this PR. I remove "sysUpTime" test in the file test_snmp_system.sh because after adding suffix ".0" to "SNMPv2-MIB::sysUpTime" it changes the name to DISMAN-EVENT-MIB::sysUpTimeInstance. SNMPv2-MIB::sysUpTime OID - 1.3.6.1.2.1.1.3 DISMAN-EVENT-MIB::sysUpTimeInstance OID: 1.3.6.1.2.1.1.3.0 (from DISMAN-EVENT-MIB.mib).

@olofhagsand  Do you have any alternative solution for that? Otherwise, this PR is ready for review.

**Comment by olofhagsand** [comment]
This is now merged, using command-line instructions. but I squashed multiple commits with same commit msg into one:
```
commit 3436a19ee4bbbd554a7c7892c3361000ed26fece (StasSt-siklu-DEV-5396-tg-snmp-snmp-walk-in-tg-not-as-snmp-in-eth-8010)
Author: stass <stas.s@siklu.com>
Date:   Mon Jan 23 19:46:39 2023 +0200

Scalars do not have a .0 suffix
See https://github.com/clicon/clixon/issues/401
```
>  I remove "sysUpTime" test in the file test_snmp_system.sh because after adding suffix ".0" to "SNMPv2-MIB::sysUpTime" it changes the name to DISMAN-EVENT-MIB::sysUpTimeInstance. SNMPv2-MIB::sysUpTime OID - 1.3.6.1.2.1.1.3 DISMAN-EVENT-MIB::sysUpTimeInstance OID: 1.3.6.1.2.1.1.3.0 (from DISMAN-EVENT-MIB.mib).

I do not have an alternative solution

**Pull request closed without merging**
