### PR TITLE
Drop __FUNCTION__ from clixon_debug() calls

### PR DESCRIPTION
**Pull request by pprindeville**
Trying to copy what `clixon_log_fn()` does.

### CODE REVIEW

**Comment by pprindeville** [comment]
Hmm... it's going to complain in a lot of places that the format string is empty, even though that's valid C...

**Comment by olofhagsand** [comment]
In what way complain?

**Comment by pprindeville** [comment]
> In what way complain?

```
In file included from ../../lib/clixon/clixon.h:79,
                 from netconf_rpc.c:71:
netconf_rpc.c: In function ‘netconf_notification_cb’:
netconf_rpc.c:462:37: warning: zero-length gnu_printf format string [-Wformat-zero-length]
  462 |     clixon_debug(CLIXON_DBG_CLIENT, "");
      |                                     ^~
../../lib/clixon/clixon_debug.h:68:97: note: in definition of macro ‘clixon_debug’
   68 | #define clixon_debug(l, _fmt, args...) clixon_debug_fn(NULL, __FUNCTION__, __LINE__, (l), NULL, _fmt, ##args)
      |                                                                                                 ^~~~
```

**Comment by pprindeville** [comment]
Okay, fixed the warnings by using `_Pragma()` expansions as part of the macro.

**Pull request merged**
